// This file will be auto-generated by running: npm run db:types
// Run this after setting up your Supabase database

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string | null
          full_name: string | null
          avatar_url: string | null
          plan: 'free' | 'pro'
          stripe_customer_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email?: string | null
          full_name?: string | null
          avatar_url?: string | null
          plan?: 'free' | 'pro'
          stripe_customer_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string | null
          full_name?: string | null
          avatar_url?: string | null
          plan?: 'free' | 'pro'
          stripe_customer_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      qrcodes: {
        Row: {
          id: string
          user_id: string | null
          data_url: string
          short_code: string
          is_dynamic: boolean
          redirect_url: string | null
          format: 'png' | 'svg' | 'pdf'
          foreground_color: string
          background_color: string
          logo_url: string | null
          title: string | null
          description: string | null
          status: 'active' | 'archived' | 'deleted'
          scan_count: number
          file_path: string | null
          created_at: string
          updated_at: string
          last_scanned_at: string | null
        }
        Insert: {
          id?: string
          user_id?: string | null
          data_url: string
          short_code: string
          is_dynamic?: boolean
          redirect_url?: string | null
          format?: 'png' | 'svg' | 'pdf'
          foreground_color?: string
          background_color?: string
          logo_url?: string | null
          title?: string | null
          description?: string | null
          status?: 'active' | 'archived' | 'deleted'
          scan_count?: number
          file_path?: string | null
          created_at?: string
          updated_at?: string
          last_scanned_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string | null
          data_url?: string
          short_code?: string
          is_dynamic?: boolean
          redirect_url?: string | null
          format?: 'png' | 'svg' | 'pdf'
          foreground_color?: string
          background_color?: string
          logo_url?: string | null
          title?: string | null
          description?: string | null
          status?: 'active' | 'archived' | 'deleted'
          scan_count?: number
          file_path?: string | null
          created_at?: string
          updated_at?: string
          last_scanned_at?: string | null
        }
      }
      scans: {
        Row: {
          id: string
          qrcode_id: string
          country: string | null
          city: string | null
          latitude: number | null
          longitude: number | null
          user_agent: string | null
          device_type: string | null
          browser: string | null
          os: string | null
          ip_address: string | null
          referrer: string | null
          scanned_at: string
        }
        Insert: {
          id?: string
          qrcode_id: string
          country?: string | null
          city?: string | null
          latitude?: number | null
          longitude?: number | null
          user_agent?: string | null
          device_type?: string | null
          browser?: string | null
          os?: string | null
          ip_address?: string | null
          referrer?: string | null
          scanned_at?: string
        }
        Update: {
          id?: string
          qrcode_id?: string
          country?: string | null
          city?: string | null
          latitude?: number | null
          longitude?: number | null
          user_agent?: string | null
          device_type?: string | null
          browser?: string | null
          os?: string | null
          ip_address?: string | null
          referrer?: string | null
          scanned_at?: string
        }
      }
      plans: {
        Row: {
          id: string
          name: string
          type: 'free' | 'pro'
          price_monthly: number | null
          price_yearly: number | null
          features: Json
          limits: Json
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          type: 'free' | 'pro'
          price_monthly?: number | null
          price_yearly?: number | null
          features?: Json
          limits?: Json
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          type?: 'free' | 'pro'
          price_monthly?: number | null
          price_yearly?: number | null
          features?: Json
          limits?: Json
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      subscriptions: {
        Row: {
          id: string
          user_id: string
          stripe_subscription_id: string
          stripe_price_id: string
          status: string
          current_period_start: string
          current_period_end: string
          cancel_at_period_end: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          stripe_subscription_id: string
          stripe_price_id: string
          status: string
          current_period_start: string
          current_period_end: string
          cancel_at_period_end?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          stripe_subscription_id?: string
          stripe_price_id?: string
          status?: string
          current_period_start?: string
          current_period_end?: string
          cancel_at_period_end?: boolean
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      plan_type: 'free' | 'pro'
      qr_format: 'png' | 'svg' | 'pdf'
      qr_status: 'active' | 'archived' | 'deleted'
    }
  }
}
